### PR TITLE
Add option for elevation correction of air pressure

### PR DESCRIPTION
**Pull request by eric-cgn**
AirThings seems to report this sensor as relative air pressure in millibars, but the readings are consistent with absolute (not relative) air pressure. This PR adds an elevation setting and corrects the absolute pressure from the sensor to relative pressure for the location.

https://help.airthings.com/en/articles/3429386-wave-plus-air-pressure-why-is-it-different

The offset between the relative and absolute pressure is constant and can be calculated based on elevation using the barometric formula:

https://en.wikipedia.org/wiki/Atmospheric_pressure#Altitude_variation

Note 1: I don't have any experience with configuration parameters in homeassistant, so please advise if this part is not done as intended.

Note 2: I did not allow airthings app to include my location during setup. If there is a correction possible on the device, I wasn't able to find any documentation about how to set any elevation parameters in the device itself, so it is unknown if this is possible, or if airthings' reported 'relative pressure' is actually 'absolute pressure' in every configuration scenario.

### CODE REVIEW

**Comment by MartyTremblay** [comment]
Nice work @eric-cgn 

I haven't tested it yet but looks promising. Note 2 might be a problem. If it is stored on the device, which I doubt it does, the workaround would be to set the atmospheric pressure to 0, correct?

**Comment by eric-cgn** [comment]
If the elevation is 0, the the offset becomes 0, so that parameter has no effect on the original sensor value and reduces to value = value + 0 in the transform function. I had a chat with airthings support to ask about how the unit could be programmed with an elevation offset (given that their own docs seem to specify this reading as "rel" pressure) and they sent me the link (in the PR) to their own help explaining why their unit gives "different values than the weather channel."

**Comment by MartyTremblay** [comment]
I haven't had the time to test this yet. Hopefully this weekend.

**Comment by ehn** [comment]
> AirThings seems to report this sensor as relative air pressure in millibars, but the readings are consistent with absolute (not relative) air pressure.

Where does it say that the reported value is relative pressure? Can't find anything about that on the AirThings website. The [article](https://help.airthings.com/en/articles/3429386-wave-plus-air-pressure-why-is-it-different) you referenced seems to confirm that the reported value is absolute pressure.

**Comment by eric-cgn** [comment]
In this project, as well as in the AirThings example code, the sensor is referred to as REL_ATM_PRESSURE... see this (official?) example code from AirThings: https://github.com/Airthings/waveplus-reader/blob/master/read_waveplus.py#L166

**Comment by ehn** [comment]
I have [asked](https://twitter.com/ehn/status/1333667078151159808) AirThings to clarify. Let's see if we get a reply.

**Comment by MartyTremblay** [comment]
I have released this feature in v2.7

**Comment by ehn** [comment]
AirThings customer service [claims that the reported value is the absolute pressure](https://twitter.com/AirthingsGlobal/status/1333793455969947649) despite the parameter name.

**Pull request merged**
