### PR TITLE
Wave plus support

### PR DESCRIPTION
**Pull request by sverrham**
Updated code to also support the airthings wave plus device.
Tested and works for me for wave plus, not tested on regular wave.

### CODE REVIEW

**Comment by MartyTremblay** [comment]
This is great work @sverrham!  I'll test this out with the regular Wave in the next couple of days.

**Comment by sverrham** [comment]
So I did a rewrite of the module since I wanted support for discovering devices, it seems to be working for me on my wave + but I have note tested it long.

Hope this makes sense and works for the regular wave also.
I think I have addressed most of the open issues with this rewrite.
Let me know if this makes sence.

**Comment by MartyTremblay** [comment]
> So I did a rewrite of the module since I wanted support for discovering devices, it seems to be working for me on my wave + but I have note tested it long.
> 
> Hope this makes sense and works for the regular wave also.
> I think I have addressed most of the open issues with this rewrite.
> Let me know if this makes sence.

Hi @sverrham , what's your setup for discovery? I'm getting an error on my Hass.io supervisor on Odroid with a USB BLE and a standard wave. I wonder if we could have device discovery disabled if the mac address is provided in the config file? Here's what i'm getting:

```
Log Details (ERROR)
Sat Feb 08 2020 15:28:35 GMT-0500 (Eastern Standard Time)
Error while setting up airthings_wave platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 166, in read_nonblocking
    s = os.read(self.child_fd, size)
OSError: [Errno 5] I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/local/lib/python3.7/site-packages/pexpect/pty_spawn.py", line 485, in read_nonblocking
    return super(spawn, self).read_nonblocking(size)
  File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 171, in read_nonblocking
    raise EOF('End Of File (EOF). Exception style platform.')
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/airthings_wave/sensor.py", line 161, in setup_platform
    devices_sensors = airthingsdetect.get_sensors()
  File "/config/custom_components/airthings_wave/airthings.py", line 178, in get_sensors
    self.adapter.start(reset_on_start=False)
  File "/usr/local/lib/python3.7/site-packages/pygatt/backends/gatttool/gatttool.py", line 289, in start
    self._con.expect(r'\[LE\]>', timeout=initialization_timeout)
  File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/local/lib/python3.7/site-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.7/site-packages/pexpect/expect.py", line 117, in expect_loop
    return self.eof(e)
  File "/usr/local/lib/python3.7/site-packages/pexpect/expect.py", line 63, in eof
    raise EOF(msg)
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0xacad47d0>
command: /usr/bin/gatttool
args: ['/usr/bin/gatttool', '-i', 'hci0', '-I']
buffer (last 100 chars): b''

after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 117
child_fd: 35
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'\\[LE\\]>')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 159, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/airthings_wave/sensor.py", line 175, in setup_platform
    _LOGGER.exception()
TypeError: exception() missing 1 required positional argument: 'msg'
```

**Comment by MartyTremblay** [comment]
I think I found the issue. /usr/bin/gatttool doesn't exist on Hass.io

**Comment by MartyTremblay** [comment]
I wonder if this approach could work?

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/bluetooth_tracker/device_tracker.py#L55

**Comment by sverrham** [comment]
Strange, I am runing Hass.io, with Home Assistant 0.103.6

**Comment by sverrham** [comment]
By the way it seems it crashed for you on get sensors, so you should have already read sensor information... 

I think you got the same error I saw after running for some time the other day. does it always crash there?

**Comment by sverrham** [comment]
Also I see the exception in the logger does not like it when it does not have a message, so I will add that now.

**Comment by sverrham** [comment]
So my conclusion from your log is that: 
If you had the mac entered you managed to connect to that device and read some information from it, then we tried to read information about the sensors and there the BLE device stoped working.

If you did not have the mac entered we managed to find an airthings device, get some information from it and then the BLE device stoped working.

Either way I whink it worked somewhat :) which makes me happy.

**Comment by MartyTremblay** [comment]
Thanks for taking the time to look into this. 

I was able to get a little further after clearing the component's pycache.

I'm now getting this

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/airthings_wave/sensor.py", line 229, in device_state_attributes
    attributes[ATTR_DEVICE_DATE_TIME] = self.device.sensordata[self._mac]['date_time']
KeyError: 'date_time'
```
I wish I could spend more time on this but it's a busy time of the year for me.

**Comment by sverrham** [comment]
No problem.
Hmm so it did not get the date_time sensor, maybe a typo or some other mistake as that is the part of the code I have not executed.

I am away the next couple of days, but could you run it with DEBUG logging and paste the log? then I could get some more information.

**Comment by MartyTremblay** [comment]
Definitely seems to be a typo or other simple issue.

```
2020-02-13 07:02:55 INFO (SyncWorker_21) [custom_components.airthings_wave.sensor] 98:07:2D:4A:97:5C: Manufacturer: Airthings AS Model: 2900 Serial: Serial Number Device:AT#132827-2900Radon
2020-02-13 07:02:55 DEBUG (SyncWorker_21) [custom_components.airthings_wave.sensor] Getting sensors
2020-02-13 07:02:55 DEBUG (SyncWorker_21) [pygatt.backends.gatttool.gatttool] gatttool_cmd=gatttool -i hci0 -I
2020-02-13 07:02:57 INFO (Thread-10) [pygatt.backends.gatttool.gatttool] Running...
2020-02-13 07:02:57 INFO (SyncWorker_21) [pygatt.backends.gatttool.gatttool] Connecting to 98:07:2D:4A:97:5C with timeout=3
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a00-0000-1000-8000-00805f9b34fb, value handle: 0x3
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a01-0000-1000-8000-00805f9b34fb, value handle: 0x5
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a04-0000-1000-8000-00805f9b34fb, value handle: 0x7
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a08-0000-1000-8000-00805f9b34fb, value handle: 0xb
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic b42e24fa-ade7-11e4-89d3-123b93f75cba, value handle: 0xe
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic b42e27ac-ade7-11e4-89d3-123b93f75cba, value handle: 0x12
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic b42e01aa-ade7-11e4-89d3-123b93f75cba, value handle: 0x16
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic b42e1096-ade7-11e4-89d3-123b93f75cba, value handle: 0x1a
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic b42e0a4c-ade7-11e4-89d3-123b93f75cba, value handle: 0x1e
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a6e-0000-1000-8000-00805f9b34fb, value handle: 0x22
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a6f-0000-1000-8000-00805f9b34fb, value handle: 0x26
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic b42e1348-ade7-11e4-89d3-123b93f75cba, value handle: 0x2a
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic f000ffc1-0451-4000-b000-000000000000, value handle: 0x2f
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic f000ffc2-0451-4000-b000-000000000000, value handle: 0x33
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic f000ffc3-0451-4000-b000-000000000000, value handle: 0x37
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a23-0000-1000-8000-00805f9b34fb, value handle: 0x3b
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a24-0000-1000-8000-00805f9b34fb, value handle: 0x3d
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a25-0000-1000-8000-00805f9b34fb, value handle: 0x3f
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a26-0000-1000-8000-00805f9b34fb, value handle: 0x41
2020-02-13 07:02:59 DEBUG (Thread-10) [pygatt.backends.gatttool.gatttool] Found characteristic 00002a29-0000-1000-8000-00805f9b34fb, value handle: 0x43
2020-02-13 07:03:02 DEBUG (SyncWorker_21) [custom_components.airthings_wave.airthings] 98:07:2D:4A:97:5C Got sensordata {'radon_1day_avg': 64.0}
2020-02-13 07:03:02 DEBUG (SyncWorker_21) [custom_components.airthings_wave.airthings] 98:07:2D:4A:97:5C Got sensordata {'radon_longterm_avg': 67.0}
2020-02-13 07:03:02 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform airthings_wave is taking over 10 seconds.
2020-02-13 07:03:02 DEBUG (SyncWorker_21) [custom_components.airthings_wave.airthings] 98:07:2D:4A:97:5C Got sensordata {'temperature': 24.2}
2020-02-13 07:03:02 DEBUG (SyncWorker_21) [custom_components.airthings_wave.airthings] 98:07:2D:4A:97:5C Got sensordata {'humidity': 22.5}
2020-02-13 07:03:03 DEBUG (SyncWorker_21) [custom_components.airthings_wave.airthings] 98:07:2D:4A:97:5C Got sensordata {'illuminance': '0.0', 'accelerometer': '0.0'}
2020-02-13 07:03:03 DEBUG (SyncWorker_21) [custom_components.airthings_wave.sensor] 98:07:2D:4A:97:5C: illuminance: 0.0
2020-02-13 07:03:03 DEBUG (SyncWorker_21) [custom_components.airthings_wave.sensor] Added sensor entity Serial Number-illuminance
2020-02-13 07:03:03 DEBUG (SyncWorker_21) [custom_components.airthings_wave.sensor] 98:07:2D:4A:97:5C: accelerometer: 0.0
2020-02-13 07:03:03 DEBUG (SyncWorker_21) [custom_components.airthings_wave.sensor] Added sensor entity Serial Number-accelerometer
2020-02-13 07:03:03 DEBUG (SyncWorker_7) [custom_components.airthings_wave.sensor] State AT#132827-2900Radon-Serial Number-illuminance 0.0
2020-02-13 07:03:03 DEBUG (SyncWorker_8) [custom_components.airthings_wave.sensor] State AT#132827-2900Radon-Serial Number-accelerometer 0.0
2020-02-13 07:03:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/airthings_wave/sensor.py", line 229, in device_state_attributes
    attributes[ATTR_DEVICE_DATE_TIME] = self.device.sensordata[self._mac]['date_time']
KeyError: 'date_time'
2020-02-13 07:03:03 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 424, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/airthings_wave/sensor.py", line 229, in device_state_attributes
    attributes[ATTR_DEVICE_DATE_TIME] = self.device.sensordata[self._mac]['date_time']
KeyError: 'date_time'
```

**Comment by MartyTremblay** [comment]
After commenting out line 229, the component registers properly but I'm missing many states. Here are the only two I'm getting so far.

```
sensor.at_132827_2900radon_serial_number_accelerometer | 8.0 | unit_of_measurement: m/s2 friendly_name: AT#132827-2900Radon-Serial Number-accelerometer icon: mdi:vibrate device_class: accelerometer
-- | -- | --
sensor.at_132827_2900radon_serial_number_illuminance | 202.0 | unit_of_measurement: lx friendly_name: AT#132827-2900Radon-Serial Number-illuminance device_class: illuminance
```

**Comment by MartyTremblay** [comment]
The good news is that i'm getting all sensor data when looking at the logs

**Comment by sverrham** [comment]
So these two latest commits should fix the strange naming of the sensors, I am using the mac now instead of the serial number and device info the airthings is reporting as that seemed strange on your wave.
Also it should fix the date time sensor not beeing available, it should both fix it so it is there but also handle it if it is not.

I am not shure that this is enough as you should have had the other sensor data when you commented out line 229, if you could test this and see if that works it would be greate, but I fear there are some other issues. I will continue to look and see if I can find something else wrong.

**Comment by MartyTremblay** [comment]
I think I see where the problem lies.

Wave plus returns all data in a single attribute which is not the case for the standard wave.

If you were to change this line
https://github.com/custom-components/sensor.airthings_wave/blob/0cc14afd4af5f784c59d75d84fbbca6990bf8d21/custom_components/airthings_wave/airthings.py#L206

to something like?

```
if self.sensordata.get(mac) == None:
  self.sensordata[mac] = sensor_data
else:
  self.sensordata[mac].update(sensor_data)
```

**Comment by sverrham** [comment]
Nice catch @MartyTremblay just replacing it with update is enough as the sensordata is initialized as a dict. Now we should be close to have something working both for pluss and the regular wave I hope :)

**Comment by sverrham** [comment]
Nice catch @MartyTremblay I first thought I had a simpler fix, pushed it without testing... 
Never push without testing :/
Your fix is what is needed, I think this should fix it. Hope it works for you now also. 
I had also another bug that I had introduced since I did not test, now the code is atleast running for me and my + device.

**Comment by MartyTremblay** [comment]
Works amazingly well @sverrham !

The refactoring is especially impressive and whatever changes you've made has also resolved issue #2 

Will merge the pull request and bump the version. Cheers!

**Pull request merged**
