### PR TITLE
Fix get_sensor_data not returning data after init

### PR DESCRIPTION
**Pull request by B1ob**

### CODE REVIEW

**Comment by B1ob** [comment]
I always had problems with airthings_wave reporting all entities as unavailable after a reboot of the host. A restart of Home Assistant then fixed this until the next reboot. After digging a bit into the problem I noticed that when setup_platform() calls get_sensor_data() the function does not do much as last_scan is still -1. My fix now also executes the first if statement in get_sensor_data() when last_scan is still -1.

**Comment by sverrham** [comment]
A bit late to the party, but I am not a fan of the change. 

Now I think the change should be to change `time.monotonic()` to `time.time()` and it should work, I just used what I used last time I did something with time, but as monotonic has an undefined reference point I guess it could be set to a value that results in `time -- 1 < scan_interval` (if using time.time() we would have time since epoc + 1 the first time and that should be larger than the scan interval causing it to enter the if statement)

**Comment by sverrham** [comment]
Hmm maybe your system has no battery and will start at time 0 when rebooting and so first time you enter this function the clock has actually not passed the scan_interval, and the os has not update the time yet...

I guess your fix will be best to handle that case, maybe not an issue with monotonic at all.
Still find it strange that the os has not update the clock before this happens, maybe you have no internet connection.

okok, I changed my mind, your fix is ok, ignore my complaints.

**Comment by B1ob** [comment]
Clock monotonic only guarantees that the time always increments (On „most“ systems it should start with 0 after boot). Therefore in my opinion it is better in this case than a wall clock, as this could be changed during runtime by the user with possible results in in strange behavior. I don’t have that much insights into the code however as i think it is used to calculate the difference of two points in time clock monotonic is perfect :) By the way i have a raspberry pi and yes it has no battery :)

**Pull request merged**
